Remove usage of humanize twig filter
zenstruck/messenger-monitor-bundle pull request #98
Opened 2024-08-06 14:24 UTC by SpartakusMd

`humanize` twig filter is used to display a human readable scheduler name. The filter uses `FormRenderer` which is available in `symfony/form`. Should the bundle drop the use of humanize? It seems too small benefit to add such a big dependency, especially for API or console projects.

Error:
> Uncaught PHP Exception Twig\Error\SyntaxError: "Did you forget to run "composer require symfony/form"? Unknown filter "humanize" in "@ZenstruckMessengerMonitor/schedule.html.twig"." at UndefinedCallableHandler.php line 99

2024-08-15 01:20 UTC, kbond commented
You're totally right. Out of curiosity, does `item.name|humanize|default(item.name)` work?

2024-08-15 08:37 UTC, SpartakusMd commented
Nope, `item.name|humanize|default(item.name)` does not work, same error that `humanize` is unknown filter.

Also while debugging, I discovered that there is also used the CSRF token from symfony/form `data-token="{{ csrf_token(['trigger', task.id, t]|join('-')) }}"` in order to retrigger a scheduled message. Would you prefer the `symfony/form` to be added as a dependency or CSRF validation removed from this specific URL?

<img width="1717" alt="image" src="https://github.com/user-attachments/assets/03543985-8f36-4eae-af91-51806e6b3888">

2024-08-20 15:03 UTC, kbond commented
We're kind of in a tough spot here. The csrf & form is only required when using the UI. This package can still be used without so I don't want to make these hard deps. I think, for now, just adding notes to the doc would be best.

In the future, the best way would be to break this package up into backend and frontend packages.
- `messenger-monitor-bundle` (backend)
- `messenger-monitor-ui-bundle` (frontend)

2024-08-22 07:09 UTC, SpartakusMd commented
Got it. Didn't remove the CSRF check and added the suggestion to install symfony/form. Still removed the humanize from the schedule name, so that it's easier understandable which schedule it is. Can revert it if needed.

2024-08-22 16:09 UTC, kbond requested changes

2024-08-22 16:09 UTC, kbond commented on README.md
> +> Necessary if when using symfony/scheduler is used.
```suggestion
> [!NOTE]
>`symfony/form` (`composer require symfony/form`) is required for the UI.
```

And let's move this to the top of this section - right after `## User Interface`

2024-08-22 16:09 UTC, kbond commented on templates/schedule.html.twig
> +                            {{ item.name }} Schedule
Let's keep humanize and just say `symfony/form` is required to use the UI.

2024-09-06 05:38 UTC, SpartakusMd commented
After some more testing, I see there are more changes required to support CSRF.
> CSRF protection is not enabled in your application. Enable it with the "csrf_protection" key in "config/packages/framework.yaml"
> CSRF protection needs sessions to be enabled.

Should I add it to the Readme too? I would rewrite the note to:
> [!NOTE]
> If using symfony/scheduler, you'll need `symfony/form` and `symfony/security-csrf`
> (`composer require symfony/form symfony/security-csrf`) and enable CSRF protection and sessions in your
> "config/packages/framework.yaml".

2024-09-27 11:31 UTC, kbond approved these changes

2024-09-27 11:36 UTC, kbond commented
@SpartakusMd, sorry for the delay here. So if not using scheduler, csrf is not required? Maybe let's have two notes then:

> [!NOTE]
> `symfony/form` (`composer require symfony/form`) is required for the UI.

> [!NOTE]
> If using `symfony/scheduler` and the UI, `symfony/security-csrf` (`composer require symfony/security-csrf`) is require. CSRF protection and sessions must also be enabled in your
`config/packages/framework.yaml`.

2024-09-27 11:57 UTC, kbond approved these changes

2024-09-27 11:57 UTC, kbond commented
Thanks for your patience @SpartakusMd!

2024-09-27 11:58 UTC, merged